/*
tuya_app_config.h
Copyright(C),2018-2020, 涂鸦科技 www.tuya.comm
*/

/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by tuya cross-build system.
* It should not be modified by hand.
*/

#ifndef TUYA_APP_CONFIG_H
#define TUYA_APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define T5AI_BOARD 1
// CONFIG_T5AI_BOARD_CELLULAR is not set
// CONFIG_T5AI_BOARD_EYES is not set
// CONFIG_T5AI_BOARD_EVB is not set
// CONFIG_T5AI_BOARD_EVB_PRO is not set
// CONFIG_T5AI_BOARD_ROBOT is not set
// CONFIG_ENABLE_TUYA_CAMERA is not set
// CONFIG_ENABLE_AUDIO_DUAL_DMIC is not set
#define ENABLE_TUYA_UI 1

#ifdef __cplusplus
}
#endif

#endif
