platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: 910bc3c93de3c988f7edca7f4c0b8d9d95c2d7c7

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: a8425530dcf866a24f4a992056bc9993a2742c10

- name: LINUX
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 98fe9dc649ee5415bc3142a41b95ae576eb04e83

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 29fcfd3d884a658ebff01c095ebcac859f55ce6b

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: e2215ada6ea9aba87fa33ac2d63bef89fa25a9f5

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 8ad5239fd9482ad66eced11677a5e64dcb5e9b4b

- name: GD32
  repo: https://github.com/tuya/TuyaOpen-GigaDevice
  branch: master
  commit: bcd898d7878ac9bea9f2a7419985afe14dd2c4d9
