platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e34a96a0963fee6d6bf50f6fc184797014464719

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: a8425530dcf866a24f4a992056bc9993a2742c10

- name: LINUX
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 0fb3ab4c531f03e383fcc3b2d20c775ba1817381

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 0353cd0a2eeda903738f5daa74384affaeb9da65

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: dev-esp32
  commit: 35bb1fc21a63f7bb2a2ee3bba348099e191179d7

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda
