import pathlib
import sys
import tempfile
import unittest
from unittest.mock import patch


ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "platform" / "JIELI"))

import platform_flash_bridge


class _Logger:
    def __init__(self):
        self.messages = []

    def info(self, message):
        self.messages.append(message)


def _make_tools_fixture(root: pathlib.Path) -> pathlib.Path:
    """A self-contained wl82 tools dir like a finished build would leave it.

    isd_config.ini is generated by make pre_build, so the bridge must find it
    next to the downloader; the fixture also keeps the tests independent of
    whatever SDK checkouts happen to be on disk.
    """
    tools = root / "chip/wl82/AC79_AIoT_SDK/cpu/wl82/tools"
    tools.mkdir(parents=True)
    (tools / "isd_download.exe").write_bytes(b"downloader")
    (tools / "isd_config.ini").write_text("VM_OPT=0;\n", encoding="utf-8")
    (tools / "uboot.boot").write_bytes(b"uboot")
    (tools / "cfg_tool.bin").write_bytes(b"cfg")
    return tools


class JieliFlashBridgeTest(unittest.TestCase):
    def test_windows_command_keeps_backslashes_and_quotes(self):
        with patch.object(platform_flash_bridge.os, "name", "nt"):
            command = platform_flash_bridge._split_command(
                r'"C:\Program Files\Jieli\isd_download.exe" --file "D:\build dir\app.bin"'
            )
        self.assertEqual(
            command,
            [
                r"C:\Program Files\Jieli\isd_download.exe",
                "--file",
                r"D:\build dir\app.bin",
            ],
        )

    def test_missing_uploader_is_reported(self):
        logger = _Logger()
        result = platform_flash_bridge.platform_flash(
            using_data={},
            binfile="/missing/jieli.bin",
            port="/dev/ttyUSB0",
            baud=115200,
            boards_root="/boards",
            logger=logger,
        )
        self.assertFalse(result["success"])
        self.assertIn("firmware image not found", result["message"])

    def test_default_windows_downloader_is_constructed(self):
        with tempfile.TemporaryDirectory() as temp:
            tools = _make_tools_fixture(pathlib.Path(temp))
            with patch.object(platform_flash_bridge.os, "name", "nt"), \
                    patch.object(platform_flash_bridge, "MODULE_ROOT", pathlib.Path(temp)):
                command = platform_flash_bridge._default_flash_command(pathlib.Path("D:/build/app.bin"))
            self.assertIsNotNone(command)
            args, tools_dir = command
            self.assertEqual(args[0], str(tools / "isd_download.exe"))
            self.assertEqual(tools_dir, tools)
            self.assertIn("-dev", args)
            self.assertIn("wl82", args)
            self.assertIn("-res", args)
            self.assertIn("cfg", args)
            self.assertIn(str(tools / "uboot.boot"), args)
            self.assertIn("D:\\build\\app.bin", args)

    def test_default_downloader_preserves_vm_area_by_default(self):
        with tempfile.TemporaryDirectory() as temp:
            tools = _make_tools_fixture(pathlib.Path(temp))
            with patch.object(platform_flash_bridge.os, "name", "nt"), \
                    patch.object(platform_flash_bridge, "MODULE_ROOT", pathlib.Path(temp)), \
                    patch.dict(platform_flash_bridge.os.environ, {"JIELI_FLASH_ERASE_VM": ""}):
                command = platform_flash_bridge._default_flash_command(pathlib.Path("D:/build/app.bin"))
            args, _ = command
            keepvm = tools / "isd_config_keepvm.ini"
            self.assertIn(str(keepvm), args)
            self.assertIn("VM_OPT=1", keepvm.read_text(encoding="utf-8"))

    def test_default_downloader_can_restore_stock_vm_erase(self):
        with tempfile.TemporaryDirectory() as temp:
            tools = _make_tools_fixture(pathlib.Path(temp))
            with patch.object(platform_flash_bridge.os, "name", "nt"), \
                    patch.object(platform_flash_bridge, "MODULE_ROOT", pathlib.Path(temp)), \
                    patch.dict(platform_flash_bridge.os.environ, {"JIELI_FLASH_ERASE_VM": "1"}):
                command = platform_flash_bridge._default_flash_command(pathlib.Path("D:/build/app.bin"))
            args, _ = command
            self.assertIn(str(tools / "isd_config.ini"), args)
            self.assertFalse((tools / "isd_config_keepvm.ini").exists())

    def test_incomplete_tools_dir_reports_build_hint(self):
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            tools = _make_tools_fixture(root)
            (tools / "isd_config.ini").unlink()
            with patch.object(platform_flash_bridge.os, "name", "nt"), \
                    patch.object(platform_flash_bridge, "MODULE_ROOT", root):
                command = platform_flash_bridge._default_flash_command(pathlib.Path("D:/build/app.bin"))
            self.assertIsNone(command)
            self.assertIn("isd_config.ini", platform_flash_bridge._flash_bridge_detail)
            self.assertIn("tos.py build", platform_flash_bridge._flash_bridge_detail)

    def test_platform_flash_runs_sdk_downloader_by_default(self):
        logger = _Logger()
        with tempfile.TemporaryDirectory() as temp:
            root = pathlib.Path(temp)
            _make_tools_fixture(root)
            image = root / "app.bin"
            image.write_bytes(b"firmware")
            completed = type("Completed", (), {"returncode": 0})()
            with patch.object(platform_flash_bridge.os, "name", "nt"), \
                    patch.object(platform_flash_bridge, "MODULE_ROOT", root), \
                    patch.dict(platform_flash_bridge.os.environ, {"JIELI_FLASH_CMD": ""}), \
                    patch.object(platform_flash_bridge.subprocess, "run", return_value=completed) as run:
                result = platform_flash_bridge.platform_flash(
                    using_data={"CONFIG_BOARD_CHOICE": "AC7916A"},
                    binfile=str(image),
                    port="",
                    baud=0,
                    boards_root="/boards",
                    logger=logger,
                )

        self.assertTrue(result, result)
        command = run.call_args.args[0]
        self.assertTrue(command[0].endswith("isd_download.exe"))
        self.assertIn("-app", command)
        self.assertIn(str(image), command)
        self.assertEqual(run.call_args.kwargs["cwd"].name, "tools")


if __name__ == "__main__":
    unittest.main()
