/* Minimal host stub of tuya_cloud_types.h for unit tests (types only). */
#ifndef __STUB_TUYA_CLOUD_TYPES_H__
#define __STUB_TUYA_CLOUD_TYPES_H__

#include <stdint.h>
#include <stddef.h>

typedef int OPERATE_RET;
#define OPRT_OK             0
#define OPRT_COM_ERROR      (-1)
#define OPRT_INVALID_PARM   (-2)
#define OPRT_MALLOC_FAILED  (-3)
#define OPRT_NOT_SUPPORTED  (-4)
#define OPRT_NOT_FOUND      (-5)

typedef uint8_t BOOL_T;
#ifndef TRUE
#define TRUE  1
#define FALSE 0
#endif

/* ---- GPIO ---- */
typedef enum {
    TUYA_GPIO_NUM_0,  TUYA_GPIO_NUM_1,  TUYA_GPIO_NUM_2,  TUYA_GPIO_NUM_3,
    TUYA_GPIO_NUM_4,  TUYA_GPIO_NUM_5,  TUYA_GPIO_NUM_6,  TUYA_GPIO_NUM_7,
    TUYA_GPIO_NUM_8,  TUYA_GPIO_NUM_9,  TUYA_GPIO_NUM_10, TUYA_GPIO_NUM_11,
    TUYA_GPIO_NUM_12, TUYA_GPIO_NUM_13, TUYA_GPIO_NUM_14, TUYA_GPIO_NUM_15,
    TUYA_GPIO_NUM_16, TUYA_GPIO_NUM_17, TUYA_GPIO_NUM_18, TUYA_GPIO_NUM_19,
    TUYA_GPIO_NUM_20, TUYA_GPIO_NUM_21, TUYA_GPIO_NUM_22, TUYA_GPIO_NUM_23,
    TUYA_GPIO_NUM_24, TUYA_GPIO_NUM_25, TUYA_GPIO_NUM_26, TUYA_GPIO_NUM_27,
    TUYA_GPIO_NUM_28, TUYA_GPIO_NUM_29, TUYA_GPIO_NUM_30, TUYA_GPIO_NUM_31,
    TUYA_GPIO_NUM_32, TUYA_GPIO_NUM_33, TUYA_GPIO_NUM_34, TUYA_GPIO_NUM_35,
    TUYA_GPIO_NUM_36, TUYA_GPIO_NUM_37, TUYA_GPIO_NUM_38, TUYA_GPIO_NUM_39,
    TUYA_GPIO_NUM_40, TUYA_GPIO_NUM_41, TUYA_GPIO_NUM_42, TUYA_GPIO_NUM_43,
    TUYA_GPIO_NUM_44, TUYA_GPIO_NUM_45, TUYA_GPIO_NUM_46, TUYA_GPIO_NUM_47,
    TUYA_GPIO_NUM_48, TUYA_GPIO_NUM_49, TUYA_GPIO_NUM_50, TUYA_GPIO_NUM_51,
    TUYA_GPIO_NUM_52, TUYA_GPIO_NUM_53, TUYA_GPIO_NUM_54, TUYA_GPIO_NUM_55,
    TUYA_GPIO_NUM_56, TUYA_GPIO_NUM_57, TUYA_GPIO_NUM_58, TUYA_GPIO_NUM_59,
    TUYA_GPIO_NUM_60, TUYA_GPIO_NUM_61, TUYA_GPIO_NUM_62, TUYA_GPIO_NUM_63,
    TUYA_GPIO_NUM_MAX,
} TUYA_GPIO_NUM_E;

typedef enum { TUYA_GPIO_LEVEL_LOW = 0, TUYA_GPIO_LEVEL_HIGH, TUYA_GPIO_LEVEL_NONE } TUYA_GPIO_LEVEL_E;
typedef enum {
    TUYA_GPIO_PULLUP = 0, TUYA_GPIO_PULLDOWN, TUYA_GPIO_HIGH_IMPEDANCE, TUYA_GPIO_FLOATING,
    TUYA_GPIO_PUSH_PULL, TUYA_GPIO_OPENDRAIN, TUYA_GPIO_OPENDRAIN_PULLUP,
} TUYA_GPIO_MODE_E;
typedef enum { TUYA_GPIO_INPUT = 0, TUYA_GPIO_OUTPUT } TUYA_GPIO_DRCT_E;
typedef struct {
    TUYA_GPIO_MODE_E  mode;
    TUYA_GPIO_DRCT_E  direct;
    TUYA_GPIO_LEVEL_E level;
} TUYA_GPIO_BASE_CFG_T;
typedef enum {
    TUYA_GPIO_IRQ_RISE = 0, TUYA_GPIO_IRQ_FALL, TUYA_GPIO_IRQ_RISE_FALL,
    TUYA_GPIO_IRQ_LOW, TUYA_GPIO_IRQ_HIGH,
} TUYA_GPIO_IRQ_E;
typedef void (*TUYA_GPIO_IRQ_CB)(void *args);
typedef struct {
    TUYA_GPIO_IRQ_E  mode;
    TUYA_GPIO_IRQ_CB cb;
    void            *arg;
} TUYA_GPIO_IRQ_T;

/* ---- ADC ---- */
typedef enum { TUYA_ADC_NUM_0 = 0, TUYA_ADC_NUM_1, TUYA_ADC_NUM_MAX } TUYA_ADC_NUM_E;
typedef enum { TUYA_ADC_INNER_SAMPLE_VOL = 0, TUYA_ADC_EXTERN_SAMPLE_VOL } TUYA_ADC_TYPE_E;
typedef enum { TUYA_ADC_SINGLE = 0, TUYA_ADC_CONTINUOUS } TUYA_ADC_MODE_E;
typedef union { uint32_t data; } TUYA_AD_DA_CH_LIST_U;
typedef struct {
    TUYA_AD_DA_CH_LIST_U ch_list;
    uint8_t              ch_nums;
    uint8_t              width;
    TUYA_ADC_MODE_E      mode;
    TUYA_ADC_TYPE_E      type;
    uint16_t             conv_cnt;
} TUYA_ADC_BASE_CFG_T;

/* ---- I2C (for headers only; unused here) ---- */
typedef enum { TUYA_I2C_NUM_0 = 0, TUYA_I2C_NUM_MAX } TUYA_I2C_NUM_E;

#endif
